---
  - name: "Install python"
    become: yes
    raw: apt -y update && apt install -y python-minimal

  - name: "Update cache"
    become: yes
    apt:
      update_cache: yes
  - name: "Upgrade packages"
    become: yes
    apt:
      upgrade: yes
  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes
  - name: "install dependencies"
    become: yes
    apt:
      name: ["nodejs","npm"]
      state: latest
      update_cache: yes
  - name: "install pm2"
    npm:
      name: pm2
      global: yes
      production: yes
      state: present