---
  - name: "Unzip Artifacts"
    become: true
    unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu/uda_people
  
  - name: "Start the app"
    command: npm i && pm2 stop default && pm2 start npm -- start
  - name: "Installing Node Dependencies"
    shell: |
      cd /home/ubuntu/uda_people
      npm i
  - name: "Executing Node app with PM2"
    shell: |
      cd /home/ubuntu/uda_people/dist
      pm2 stop default
      pm2 start main.js
    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"

  - name: "Configure pm2 to start as service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu