---
  - name: "Create app directory"
    become: true
    file:
      path: /home/ubuntu/uda_people
      state: directory
    
  - name: "Unzip Artifacts"
    become: true
    unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu/uda_people
  
  - name: "Installing Node Dependencies"
    become: true
    shell: |
      cd /home/ubuntu/uda_people
      npm i
  - name: "Executing Node app with PM2"
    become: true
    shell: |
      cd /home/ubuntu/uda_people/dist
      pm2 stop default
      pm2 start main.js

  - name: "Configure pm2 to start as service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu